models/physicals.py
"""
This file have the model
for the physicals notes.
"""

from utils.db import db

class Physicals(db.Model):
  """
  Model for the notes physicals

  id not null
  name varchar(50)
  note integer
  """

  id = db.Column(db.Integer, primary_key = True)
  student = db.Column(db.String(50))
  note = db.Column(db.Integer)

  def __init__(self, student:str, note:str) -> None:
      # values
      self.student = student
      self.note = note

models/quizs.py
"""
This file have the model
of the note for the database.
"""

from utils.db import db

class Quizs(db.Model):
  """
  Model for the Quiz notes
  id not null
  name varchar(50)
  note integer
  """

  id = db.Column(db.Integer, primary_key = True)
  student = db.Column(db.String(50))
  note = db.Column(db.Integer)

  def __init__(self, student:str, note:str) -> None:
      # values
      self.student = student
      self.note = note

app.py
"""
This file have the configuration for the server.
Only configurations, run with index.py
"""

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from routes.results import results
from config import CONNECTION

# creating
app = Flask(__name__)

# settings
app.config['SQLALCHEMY_DATABASE_URI'] = CONNECTION
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

SQLAlchemy(app)

# routes
app.register_blueprint(results)

routes/results.py
"""
This file have the routes
for use in the website.
"""

from flask import Blueprint, render_template
from models.physicals import Physicals
from models.quizs import Quizs
from models.physicals import Physicals

results = Blueprint('results', __name__)

@results.route('/')
def home():
  """
  Principal route /
  """

  # getting results for pass to page
  quizs_results = Quizs.query.all()
  physicals_results = Physicals.query.all()

  # changing int to str of note
  for result in quizs_results:
    result.note = int(result.note)

  for result in physicals_results:
    result.note = int(result.note)

  return render_template(
    'index.html',
    quizs_results = quizs_results,
    physicals_results = physicals_results
  )

@results.route('/contacts')
def contacts():
  """
  Route for show the page
  of the contacts
  """

  return render_template('contacts.html')


@results.route('/more')
def more():
  """
  Route for show the page
  of more
  """

  return render_template('more.html')

templates/contacts.html
<!-- PAGE FOR THE CONTACTS -->
{% extends 'layout.html' %}

{% block body %}

<link rel="stylesheet" href="{{ url_for('static', filename = 'css/contacts.css') }}">

<h1 class="text-white mb-4">Contacts <i class="far fa-address-book m-3"></i></h1>
<p class="description mb-2">These are some contacts <span id="resalt">of the school</span></p>
<hr class="text-white mb-5">

<!-- VIEW OF CONTACTS -->
<div class="view-contacts">
  <div class="contact">
    <h3 class="mb-3">Director</h3>
    <p class="phone">7823-8432</p>
    <button class="btn btn-primary">Contact</button>
  </div>

  <div class="contact">
    <h3 class="mb-3">Miss Carmen</h3>
    <p class="phone">79125-2461</p>
    <button class="btn btn-primary">Contact</button>
  </div>

  <div class="contact">
    <h3 class="mb-3">Mister Gonzalo</h3>
    <p class="phone">7263-7133</p>
    <button class="btn btn-primary">Contact</button>
  </div>

  <div class="contact">
    <h3 class="text-dark mb-3">Miss Lorena</h3>
    <p class="phone">7717-1911</p>
    <button class="btn btn-primary">Contact</button>
  </div>

  <div class="contact">
    <h3 class="mb-3">Miss Karla</h3>
    <p class="phone">7512-6523</p>
    <button class="btn btn-primary">Contact</button>
  </div>

  <div class="contact">
    <h3 class="mb-3">Mister Pablo</h3>
    <p class="phone">7451-4613</p>
    <button class="btn btn-primary">Contact</button>
  </div>

</div>

{% endblock %}

templates/index.html
<!-- PRINCIPAL PAGE -->
{% extends 'layout.html' %}

{% block body %}

<!-- PRINCIPAL VIEW -->
<section class="view">
  <p class="pt-4 description">The quiz's results of a <span class="text-muted">Scholl.</span>Lorem ipsum
    dolor sit amet consectetur adipisicing elit. Numquam fugit incidunt blanditiis ipsam odit itaque enim harum esse
    similique distinctio optio quaerat ex, necessitatibus repellendus odio illum officiis assumenda id! Placeat
    obcaecati amet iste beatae dolor quaerat commodi totam incidunt illum reiciendis ad quam architecto dolore, nisi
    iure quos error exercitationem, enim non vero voluptates asperiores optio. Quibusdam, aperiam quam! Lorem ipsum
    dolor sit amet consectetur adipisicing elit. Voluptate dicta nulla tenetur dolor adipisci quibusdam rerum magni
    aperiam cumque minima, totam quia, hic quas aut commodi. Reiciendis totam nostrum itaque perspiciatis labore sed
    ducimus quam impedit suscipit, quisquam id fuga molestias officiis, deleniti tempora facere ea iste repellat
    aut? Natus.

    <a class="link d-block mt-3" href="#">Learn More</a>
  </p>

  <!-- DATA VIEW -->
  <div class="data-view">
    <h3 class="text-white">Principals results</h3>

    <hr class="text-white">

    <!-- if exists results -->
    {% if quizs_results %}
    <table class="table">
      <tr>
        <th class="text-center">Student</th>
        <th class="text-center">Note</th>
      </tr>

      {% for result in quizs_results %}
      <tr>
        <td>{{ result.student }}</td>
        <!-- here we validate the notes -->
        <td class="text-center"
          style="{% if result.note > 8 %}background-color: #aaffaa; {% elif result.note <= 8 and result.note > 5 %} background-color: #ffffaa; {% else %} background-color:#ffaaaa; {% endif %}">
          {{ result.note }}
        </td>
      </tr>
      {% endfor %}

    </table>

    {% else %}
    <h3 class="text-white p-4">Not results yet.</h3>
    {% endif %}

  </div>

</section>

<!-- INFO 1 -->
<div class="p-4 info">
  <p class="text-center text-dark">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis recusandae,
    officiis illo perspiciatis expedita quae a, ratione accusamus praesentium assumenda quas impedit! Blanditiis enim
    in laboriosam voluptatibus quod. Dignissimos fugit architecto, tenetur doloribus facere optio dicta! Accusantium,
    autem expedita laborum ex nisi mollitia qui eius non facilis minima pariatur, laboriosam, consectetur totam
    maiores natus odio quasi et laudantium? Esse molestias quam praesentium libero voluptates earum inventore
    similique, aut amet accusantium accusamus dolore eveniet provident quos reiciendis officiis sunt nulla placeat,
    corporis, numquam optio et architecto. Quis, ex. Sit quibusdam nobis ullam nesciunt, veritatis, dicta animi,
    eveniet omnis voluptas praesentium aspernatur!</p>
</div>

<hr class="text-white mb-5">

<div class="more-results mb-5">
  <h3 class="text-white mb-4">More results</h3>

  <div class="more-view">

    <p class="more-description">Others results of the students in <span class="text-muted">physicals tests</span>, Lorem
      ipsum dolor sit, amet consectetur adipisicing elit.
      Itaque cum blanditiis quaerat repudiandae repellat dolore facilis at animi, asperiores est accusantium voluptas!
      Quibusdam, accusamus! Officia explicabo, vel corrupti voluptatibus sunt rem qui earum, quam ducimus
      necessitatibus consectetur amet non numquam modi voluptates distinctio fugit tempora delectus atque perferendis.
      Libero, possimus?
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Necessitatibus commodi tempore impedit reiciendis
      accusamus eveniet, temporibus accusantium ut quae, pariatur cupiditate rem architecto fugiat laboriosam cum
      nemo, id fuga obcaecati vitae officia maiores nesciunt. A nobis laboriosam error, voluptas voluptates
      perferendis molestiae hic natus facere expedita alias reprehenderit nam quam.
      <br>
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestias blanditiis quo, illo maxime quae animi
      quibusdam, totam praesentium temporibus sit repellat voluptatem. Dignissimos ex harum fuga natus error in quia
      vel neque aperiam? Debitis aliquam ab laborum, odio necessitatibus omnis non quae, reiciendis commodi
      accusantium inventore beatae neque odit amet!
    </p>

    <!-- if exists results -->
    {% if physicals_results %}
    <table class="table">
      <tr>
        <th class="text-center">Student</th>
        <th class="text-center">Note</th>
      </tr>

      {% for result in physicals_results %}
      <tr>
        <td>{{ result.student }}</td>
        <!-- here we validate the notes -->
        <td class="text-center"
          style="{% if result.note > 8 %}background-color: #aaffaa; {% elif result.note <= 8 and result.note > 5 %} background-color: #ffffaa; {% else %} background-color:#ffaaaa; {% endif %}">
          {{ result.note }}
        </td>
      </tr>
      {% endfor %}

    </table>

    {% else %}
    <h3 class="text-white p-4">Not results yet.</h3>
    {% endif %}
  </div>
</div>

<!-- BUTTON -->
<a class="mb-5 btn btn-secondary" href="#title">Go to begin</a>

<hr class="text-white">

<!-- INFO 2 -->
<div class="mt-4 p-4 info">
  <p class="text-center text-dark">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis recusandae,
    officiis illo perspiciatis expedita quae a, ratione accusamus praesentium assumenda quas impedit! Blanditiis enim
    in laboriosam voluptatibus quod. Dignissimos fugit architecto, tenetur doloribus facere optio dicta! Accusantium,
    autem expedita laborum ex nisi mollitia qui eius non facilis minima pariatur, laboriosam, consectetur totam
    maiores natus odio quasi et laudantium? Esse molestias quam praesentium libero voluptates earum inventore
    similique, aut amet accusantium accusamus dolore eveniet provident quos reiciendis officiis sunt nulla placeat,
    corporis, numquam optio et architecto. Quis, ex. Sit quibusdam nobis ullam nesciunt, veritatis, dicta animi,
    eveniet omnis voluptas praesentium aspernatur!</p>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Results Website.</title>
  <!-- BOOTSTRAP -->
  <link rel="stylesheet" href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}">

  <!-- FONTAWESOME -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  <!-- CUSTOM STYLE -->
  <link rel="stylesheet" href="{{ url_for('static', filename = 'css/custom.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename = 'css/table.css') }}">
  <link rel="shortcut icon" href="{{ url_for('static', filename = 'img/logo.ico') }}" type="image/x-icon">
</head>

<body>

  <header>
    <!-- NAV -->
    {% include 'partials/_nav.html' %}
  </header>

  <div class="container mt-5">
    {% block body %}
    {% endblock %}
  </div>


  <!-- FOOTER -->
  <footer class="p-2 text-center">
    <p class="">2021</p>
    <a class="text-dark" href="mailto:helptest@gmail.com">Help</a>
  </footer>

  <!-- SCRIPTS -->
  <script src="{{ url_for('static', filename = 'js/bootstrap.min.js') }}"></script>
  <!-- <script src="{{ url_for('static', filename = 'js/app.js') }}" type="module"></script> -->

</body>

</html>

templates/more.html
<!-- MORE PAGE -->
{% extends 'layout.html' %}

{% block body %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/more.css') }}">

<!-- VIEW INFO -->
<section class="view-info">

  <div class="p-4 info">
    <p class="mb-5">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis soluta deleniti facere! Adipisci suscipit ullam accusantium reprehenderit deleniti quaerat vero veritatis inventore. Suscipit, placeat? Placeat, repellat libero cumque suscipit laboriosam eos et nam, mollitia nulla dolores quo eligendi enim ipsa aliquid animi saepe, rerum nemo aliquam expedita dolore obcaecati! <span class="line">Consectetur rerum tenetur adipisci fuga. Ut, saepe dolores? Exercitationem eaque quas nam fuga consectetur laudantium ducimus nostrum tempore facilis quis, ut numquam quaerat officiis incidunt repellat quasi eius veritatis deserunt accusantium id</span> repellendus modi, labore itaque. Delectus culpa, sapiente numquam magni ad nam. Repudiandae provident minima molestias necessitatibus corporis, earum repellat.
    </p>
    <button class="btn">Learn More</button>

  </div>

  <div class="p-4 info">
    <p class="mb-5">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto velit mollitia, dolores, fugiat suscipit impedit modi adipisci nobis consequuntur, nisi ducimus exercitationem tempore ratione optio minus maiores blanditiis expedita architecto quae veritatis consequatur dignissimos sit nemo. Dolorem, quaerat sapiente. Expedita adipisci assumenda iure quaerat ea fuga officiis cumque aliquam perspiciatis. Similique neque molestias voluptas odio, <span class="line"> nisi ullam quam commodi at incidunt voluptatibus in laudantium error itaque voluptates. Eius sit voluptatum fugiat earum perferendis beatae praesentium, aut incidunt omnis velit quod aliquam sunt reiciendis quibusdam cumque. Porro, expedita earum. </span>Quos corporis unde deserunt ullam, alias expedita provident quidem aperiam obcaecati.
    </p>
    <button class="btn">Learn More</button>

  </div>

  <div class="p-4 info">
    <p class="mb-5">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid dolorem fugit eum odio tenetur laudantium deleniti commodi rem! Soluta, enim molestias? Quos magni sit dignissimos magnam doloribus nisi minima nemo, tempora corporis fugiat <span class="line">aliquam pariatur nam consequatur praesentium totam. Officia nihil adipisci officiis beatae dignissimos nemo qui consequuntur.</span> Tempora sunt, eius libero aliquam possimus fugit dignissimos ipsam reiciendis consequuntur voluptatum sequi enim unde, ducimus id aliquid eligendi illum ut fuga ullam impedit, ea maiores eaque dolorem? Distinctio corporis rerum tenetur, nemo a aliquid excepturi. Enim dolores repellendus nemo fugiat eum esse voluptas quasi cumque, sapiente maxime ratione libero sequi quod.
    </p>
    <button class="btn">Learn More</button>
  </div>

</section>

{% endblock %}

templates/partials/_nav.html
<!-- NAV FOR USE -->
<nav class="nav">
  <ul class="navbar-left">
    <li>
      <a href="{{ url_for('results.home') }}" id="title">Results Website</a>
    </li>
  </ul>

  <ul class="navbar-right">
    <li>
      <a href="{{ url_for('results.more') }}">
        <i class="fas fa-info-circle"></i>
        More
      </a>
    </li>
    <li>
      <a href="{{ url_for('results.contacts') }}">
        <i class="far fa-address-book"></i>
        Contacts
      </a>
    </li>
  </ul>
</nav>